### ISSUE TITLE
Kata: content-directives

### ISSUE THREAD

**Issue by danielkull** [danielkull/vue-coding-task#1]
Performe coding kata:

# Task: Content directives

In this task we use the `content directives`. Sources will be found in the `src` folder of this directory.

Fulfill the following tasks:

- [x] Write all your js code in the `scripts.js` file
- [x] Seems like the Vue Instance has no connection to the DOM node fix it.
- [x] The headline contains the wrong vue version. The version increases every two seconds.
  - [x] Figure out why and solve the problem
  - [x] Ensure that the version does not count up on the screen. Only the initial value of the data property should displayed. Do not remove the setInterval in the mount method. Use a directive!
- [x] Render the data property text as HTML
- [x] The mustache tags should not get rendered. They should get printed out on the screen
- [x] All errors in the devTools console are removed
