### ISSUE TITLE
Event Handling

### ISSUE THREAD

**Issue by danielkull** [danielkull/vue-coding-task#10]
# Task: Event Handling

In this task we use the `Event Handling` of vueJS.

You will find all needed resources to get started in the `src` folder. Use them as a starting point and try to solve the tasks below.

## Task 1

Given is a rectangle with a red rectangle inside of it. The goal is to update the coordinates when the mouse moves over the rectangle. .

- [x] Add an mousemove event to the div container and update
  - [x] Update the data properties x and y with the current coordinates of the mouse position.
  - [x] Ensure that the coordinates getting displayed on the screen.
- [x] There is a red dead spot in the middle of the mousemove element. The coordinates should not get updated when mouse moves over the spot.

## Task 2

Given is a list of fruits but the remove button is not working yet.

- [x] Implement functionality to remove each entry from the list with the given remove button.
- [x] Take use of v-on directive and methods.
