### ISSUE TITLE
Setup a Vue Project with Vue CLI

### ISSUE THREAD

**Issue by danielkull** [danielkull/vue-coding-task#11]
# Task: Setup a Vue Project with Vue CLI

You will need a Vue CLI installation for the upcoming tasks. Please create a project with the following configuration.

- Please pick a preset: 
  - [x] Manually select features
- Check the features needed for your project: 
  - [x] Choose Vue version
  - [x] Babel
  - [x] Linter / Formatter
- Choose a version of Vue.js that you want to start the project with: 
  - [x] 3.x
- Pick a linter / formatter config:
  - [x] ESLint + Prettier
- Pick additional lint features: 
  - [x] Lint on save
- Where do you prefer placing config for Babel, ESLint, etc.?
  - [x] In dedicated config files
- Save this as a preset for future projects?
  - [x] No

**Comment by danielkull** [comment]
[How to Set Alias](https://dev.to/mhjaafar/git-bash-on-windows-adding-a-permanent-alias-198g)
[How to fix Windows Bash 'vue' comand with Alias](https://stackoverflow.com/questions/51297079/vue-cli-arrow-key-not-working-while-creating-new-project-on-git-bash-windows)
Note: Alias were writen in "aliases.sh" in the respective git folder ./etc/profile.d
