### ISSUE TITLE
Task: Add a reset.css file

### ISSUE THREAD

**Issue by danielkull** [danielkull/vue-coding-task#13]
# Task: Add a reset.css file

We need to normalize some styling

- [ ] Remove all styles from existing files.
- [ ] Add the `src/reset.css` css styles to the application
  - [ ] Use one of the techniques you learned before
