### ISSUE TITLE
Task: Header & Booklist Component

### ISSUE THREAD

**Issue by danielkull** [danielkull/vue-coding-task#14]
# Task: Header & Booklist Component

In this task we will practice the handling with single file components in Vue CLI projects.

## Solve the following tasks:

- [x] Remove the HelloWorld component
- [x] Remove dummy stuff from App.vue
- [x] Add global css styles from `src/global.css`
  - [x] Choose your favorite technique to add css
- [x] Create a Header Component
  - [x] Take use of provided resources `src/LayoutHeader`
  - [x] Register it in the App.vue
- [x] Create a BookList Component
  - [x] Take use of provided resources `src/BookList`
  - [x] Register it in the App.vue
