### ISSUE TITLE
attribute-binding

### ISSUE THREAD

**Issue by danielkull** [danielkull/vue-coding-task#3]
# Task: Attribute binding

In this task we use the `attribute binding`. Sources will be found in the `src` folder of this directory.

Fulfill the following tasks:

- [x] Write all your js code in the `scripts.js` file
- [x] Convert the headline data property into a valid id and set the ID to the `h1`
- [x] Bind the data property `imageAttrs` to the `img` tag.
