### ISSUE TITLE
Kata: class-bindings

### ISSUE THREAD

**Issue by danielkull** [danielkull/vue-coding-task#5]
# Task: Class Binding

In this task we use the `class binding`. Sources will be found in the `src` folder of this directory.
There exists a tab content block. It has two part the tab navigator and the content. The current active tab should be always in sync with the displayed content.

Fulfill the following tasks:

- [x] Write all your js code in the `scripts.js` file
- [x] Use the data property `activeTab` to set a tab as active
  - [x] set the right css class to the current active tab navigation item by using conditional class list rendering
  - [x] ensure that you display the right content by using the right css class and conditional class list rendering
