### ISSUE TITLE
Kata: conditional-rendering

### ISSUE THREAD

**Issue by danielkull** [danielkull/vue-coding-task#7]
# Task: Conditional rendering

In this task we use the `conditional rendering`. Sources will be found in the `src` folder of this directory.
There exists a tab content block. It has two part the tab navigator and the content. The current active tab should be always in sync with the displayed content.

Fulfill the following tasks:

- [x] Write all your js code in the `scripts.js` file
- [x] Use the data property `activeTab` to set a tab as active
  - [x] Use v-if to display the right content block.
  - [x] Content and tab should be always in sync.
  - [x] display a excuse fallback text when there is no match for an active tab.
    - Could happen when `activeTab` is higher or lower than the amount of available tabs
