### ISSUE TITLE
List rendering

### ISSUE THREAD

**Issue by danielkull** [danielkull/vue-coding-task#8]
# Task: List rendering

In this task we use the `list rendering`. Sources will be found in the `src` folder of this directory.

The task is about rendering a table of books that are provided by a data property `books`.

Fulfill the following tasks:

- [ ] Write all your js code in the `scripts.js` file
- [ ] Generate the table head by getting the `keys` of one book data set
- [ ] Display all books in the table

## Hint

- With Object.keys() you can get an array with only the keys of an Object
